// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_code, long_url) VALUES ($1, $2) RETURNING id, short_code, long_url, clicks
`

type CreateLinkParams struct {
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
}

type CreateLinkRow struct {
	ID        int64  `json:"id"`
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
	Clicks    int32  `json:"clicks"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ShortCode, arg.LongUrl)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
	)
	return i, err
}

const getClicksByCode = `-- name: GetClicksByCode :one
SELECT clicks FROM links WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetClicksByCode(ctx context.Context, shortCode string) (int32, error) {
	row := q.db.QueryRow(ctx, getClicksByCode, shortCode)
	var clicks int32
	err := row.Scan(&clicks)
	return clicks, err
}

const getURLAndIncrementLinkClicks = `-- name: GetURLAndIncrementLinkClicks :one
UPDATE links SET clicks = clicks + 1 WHERE short_code = $1 RETURNING long_url
`

func (q *Queries) GetURLAndIncrementLinkClicks(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getURLAndIncrementLinkClicks, shortCode)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
