// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_code, long_url) VALUES ($1, $2) RETURNING id, short_code, long_url, clicks
`

type CreateLinkParams struct {
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
}

type CreateLinkRow struct {
	ID        int64  `json:"id"`
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
	Clicks    int32  `json:"clicks"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ShortCode, arg.LongUrl)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
	)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT id, short_code, long_url, clicks, created_at FROM links WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetLinkByCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}
